name: Build website
on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: nicolecomputer/quartz
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - run: "rm -rf content"
      - uses: actions/checkout@v4
        with:
          repository: nicolecomputer/nicole-notes
          path: "content"
      - run: npx quartz build
      - run: "ls"
