name: Build website
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: nicolecomputer/quartz
          path: quartz
      - run: "cd quartz; bash build.sh; ls public"
